name: Primer workflow

on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola GH Actions"
      - name: Bajar código
        uses: actions/checkout@v4
      - name: Probar código
        run: python3 main.py
